source ./venv/bin/activate

python resultLinerarityRHttpReqExecTime.py
python resultQueryContainmentTable.py
python resultRatioUsefulSources.py

python resultVariationPercentageShapeIndex.py
python resultVariationPercentageEntry.py
python resultVariationShapeDetail.py
python resultVariationApproach.py

python resultVariationShapeIndexAll.py